#include <bits/stdc++.h>
using namespace std;

void solve(std::string S)
{
    int ans = 0;
    for (int i = 0; i < S.size(); i++)
    {
        if (S[i] == '+')
        {
            ans++;
        }
        else
        {
            ans--;
        }
    }
    cout << ans << endl;
}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
