#include <bits/stdc++.h>
using namespace std;


void solve(long long M, long long K){

}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long M;
    scanf("%lld",&M);
    long long K;
    scanf("%lld",&K);
    solve(M, K);
    return 0;
}
