import java.io.BufferedInputStream



// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
fun main(args: Array<String>) {
    fun StringArray(size: Int, init: (Int) -> String = { "\u0000" }): Array<String> {
        return Array<String>(size, init)
    }
    fun iterateTokens(): Iterator<String> {
        val reader = BufferedInputStream(System.`in`).bufferedReader()
        val iterator = reader.lineSequence()
                .map { it.split(" ") }
                .reduce { left, right -> left + right }
                .iterator()
        return iterator
    }
    val tokens = iterateTokens()
    val N = tokens.next().toLong()
    val g_A = tokens.next().toLong()
    val s_A = tokens.next().toLong()
    val b_A = tokens.next().toLong()
    val g_B = tokens.next().toLong()
    val s_B = tokens.next().toLong()
    val b_B = tokens.next().toLong()
    solve(N, g_A, s_A, b_A, g_B, s_B, b_B)
}

fun solve(N: Long, g_A: Long, s_A: Long, b_A: Long, g_B: Long, s_B: Long, b_B: Long){
    return
}

