import java.io.BufferedInputStream



// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
fun main(args: Array<String>) {
    fun StringArray(size: Int, init: (Int) -> String = { "\u0000" }): Array<String> {
        return Array<String>(size, init)
    }
    fun iterateTokens(): Iterator<String> {
        val reader = BufferedInputStream(System.`in`).bufferedReader()
        val iterator = reader.lineSequence()
                .map { it.split(" ") }
                .reduce { left, right -> left + right }
                .iterator()
        return iterator
    }
    val tokens = iterateTokens()
    val N = tokens.next().toLong()
    val x = LongArray(N.toInt())
    val y = LongArray(N.toInt())
    for(i in 0 until N.toInt()){
        x[i] = tokens.next().toLong()
        y[i] = tokens.next().toLong()
    }
    solve(N, x, y)
}

fun solve(N: Long, x: LongArray, y: LongArray){
    return
}

