#include <bits/stdc++.h>
using namespace std;


void solve(long long n){

}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long n;
    scanf("%lld",&n);
    solve(n);
    return 0;
}
