import java.io.BufferedInputStream



// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
fun main(args: Array<String>) {
    fun StringArray(size: Int, init: (Int) -> String = { "\u0000" }): Array<String> {
        return Array<String>(size, init)
    }
    class Scanner() {
        private val reader = BufferedInputStream(System.`in`).bufferedReader()
        private val tokens = StringTokenizer(reader.use { it.readText() })
        fun next() = tokens.nextToken()
    }
    val sc = Scanner()
    val W = tokens.next().toLong()
    val H = tokens.next().toLong()
    val x = tokens.next().toLong()
    val y = tokens.next().toLong()
    solve(W, H, x, y)
}

fun solve(W: Long, H: Long, x: Long, y: Long){
    return
}

