#include <bits/stdc++.h>
using namespace std;


void solve(std::vector<long long> H){

}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::vector<long long> H(2);
    for(int i = 0 ; i < 2 ; i++){
        scanf("%lld",&H[i]);
    }
    solve(std::move(H));
    return 0;
}
