#include <bits/stdc++.h>
using namespace std;


void solve(std::string A){

}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string A;
    std::cin >> A;
    solve(A);
    return 0;
}
