#include <bits/stdc++.h>
using namespace std;

const long long MOD = 10007;

void solve(long long L, long long A, long long B, long long M){

}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long L;
    scanf("%lld",&L);
    long long A;
    scanf("%lld",&A);
    long long B;
    scanf("%lld",&B);
    long long M;
    scanf("%lld",&M);
    solve(L, A, B, M);
    return 0;
}
