#!/usr/bin/env python3
import sys


def solve(s: str, k: int):
    pass_list = []
    for i in range(len(s)-k+1):
        pass_list.append(s[i:i+k])
    print(len(list(set(pass_list))))
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    s = next(tokens)  # type: str
    k = int(next(tokens))  # type: int
    solve(s, k)

if __name__ == '__main__':
    main()
