#include <bits/stdc++.h>
using namespace std;

void solve(long long N, vector<long long> W)
{
    long long ans = 1000000000;
    for (int i = 0; i < N; i++)
    {
        long long s1 = accumulate(W.begin(), W.begin() + i, 0LL);
        long long s2 = accumulate(W.begin() + i, W.end(), 0LL);
        ans = min(ans, abs(s1 - s2));
    }
    cout << ans << endl;
}

// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    std::vector<long long> W(N);
    for (int i = 0; i < N; i++)
    {
        scanf("%lld", &W[i]);
    }
    solve(N, std::move(W));
    return 0;
}
