#!/usr/bin/env python3
import sys

MOD = 1000000007  # type: int


def adjacent(S, x, y):
    return


def solve(N: int, S: "List[str]"):
    for y in range(2):
        for x in range(N):
            pass
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word

    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(2)]  # type: "List[str]"
    solve(N, S)


if __name__ == '__main__':
    main()
